language: node_js
node_js: "10"

os:
  - osx
  - linux

env:
  - NODE_ENV="test"

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - yarn
  - yarn vscode:prepublish
  - yarn test

after_success:
  - npm run coverage

cache: yarn